language: python

python:
    - "2.7"
    - "3.5"

install:
 - pip install .
 - pip install matplotlib
 - pip install coverage codecov

dist: xenial

services:
  - xvfb #X Virtual Framebuffer

script:
 - coverage run -m unittest discover --pattern=*.py -s omas/tests

after_success:
 - codecov
